---
name: Maven Build
"on": [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        java: [1.8, 11, 13]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - name: Build it with Maven
        run: mvn -B verify -Pqulice
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
         file: ./target/site/jacoco/jacoco.xml
         name: codecov-artipie-go-adapter
         fail_ci_if_error: true
